--- #YAML:1.0
name: Finance-Card-Citibank
version: 1.01
author:
  - Mark V. Grimes<mgrimes@cpan.org>
abstract: |-
  Check your Citigroup credit card accounts from Perl
license: perl
requires:
  Carp: 0
  WWW::Mechanize: 1
provides:
  Finance::Card::Citibank:
    file: lib/Finance/Card/Citibank.pm
    version: 1.01
  Finance::Card::Citibank::Account:
    file: lib/Finance/Card/Citibank.pm
    version: 1.01
generated_by: Module::Build version 0.2611
